//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car24project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class avtoAdvt
    {
        public int id { get; set; }
        public int price { get; set; }
        public byte[] photo { get; set; }
        public int markaID { get; set; }
        public int modelID { get; set; }
        public int bodyType { get; set; }
        public int colorID { get; set; }
        public int engineVolumeID { get; set; }
        public int motorPowerID { get; set; }
        public int fuelTypeID { get; set; }
        public int graduationYearID { get; set; }
        public int mileage { get; set; }
        public int driveUintID { get; set; }
        public int transmissionID { get; set; }
        public string additionalInfo { get; set; }
        public int phone { get; set; }
        public string contactsName { get; set; }
        public System.DateTime publicDate { get; set; }
        public Nullable<int> viewSize { get; set; }
        public int avtoAdvtGalleryİD { get; set; }
    
        public virtual bodyType bodyType1 { get; set; }
        public virtual color color { get; set; }
        public virtual driveUnit driveUnit { get; set; }
        public virtual engineVolume engineVolume { get; set; }
        public virtual fuelType fuelType { get; set; }
        public virtual graduationYear graduationYear { get; set; }
        public virtual marka marka { get; set; }
        public virtual model model { get; set; }
        public virtual motorPower motorPower { get; set; }
        public virtual transmission transmission { get; set; }
        public virtual avtoAdvtGallery avtoAdvtGallery { get; set; }
    }
}
