//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car24project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Car24DataEntities : DbContext
    {
        public Car24DataEntities()
            : base("name=Car24DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autoShops> autoShops { get; set; }
        public virtual DbSet<avtoAdvt> avtoAdvt { get; set; }
        public virtual DbSet<bodyType> bodyType { get; set; }
        public virtual DbSet<car_characteristic> car_characteristic { get; set; }
        public virtual DbSet<car_characteristic_value> car_characteristic_value { get; set; }
        public virtual DbSet<carWash> carWash { get; set; }
        public virtual DbSet<cat> cat { get; set; }
        public virtual DbSet<clubs> clubs { get; set; }
        public virtual DbSet<color> color { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<driveUnit> driveUnit { get; set; }
        public virtual DbSet<engineVolume> engineVolume { get; set; }
        public virtual DbSet<fuelType> fuelType { get; set; }
        public virtual DbSet<gender> gender { get; set; }
        public virtual DbSet<graduationYear> graduationYear { get; set; }
        public virtual DbSet<marka> marka { get; set; }
        public virtual DbSet<marka_cat> marka_cat { get; set; }
        public virtual DbSet<marka_norm> marka_norm { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<model> model { get; set; }
        public virtual DbSet<motorPower> motorPower { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<newsCategories> newsCategories { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<sities> sities { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<transmission> transmission { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<usersType> usersType { get; set; }
        public virtual DbSet<car_generation> car_generation { get; set; }
        public virtual DbSet<car_model> car_model { get; set; }
        public virtual DbSet<car_modification> car_modification { get; set; }
        public virtual DbSet<gallery> gallery { get; set; }
        public virtual DbSet<model_marka_cat> model_marka_cat { get; set; }
        public virtual DbSet<car_serie> car_serie { get; set; }
        public virtual DbSet<avtoAdvtGallery> avtoAdvtGallery { get; set; }
        public virtual DbSet<reklam> reklam { get; set; }
    }
}
