//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car24project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_modification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public car_modification()
        {
            this.car_characteristic_value = new HashSet<car_characteristic_value>();
        }
    
        public int id_car_modification { get; set; }
        public int id_car_serie { get; set; }
        public int id_car_model { get; set; }
        public string name { get; set; }
        public Nullable<int> start_production_year { get; set; }
        public Nullable<int> end_production_year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<car_characteristic_value> car_characteristic_value { get; set; }
        public virtual car_model car_model { get; set; }
    }
}
