//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car24project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_generation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public car_generation()
        {
            this.car_serie = new HashSet<car_serie>();
        }
    
        public int id_car_generation { get; set; }
        public string name { get; set; }
        public int id_car_model { get; set; }
        public string year_begin { get; set; }
        public string year_end { get; set; }
    
        public virtual car_model car_model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<car_serie> car_serie { get; set; }
    }
}
