//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car24project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_serie
    {
        public int id_car_serie { get; set; }
        public int id_car_model { get; set; }
        public string name { get; set; }
        public Nullable<int> id_car_generation { get; set; }
    
        public virtual car_generation car_generation { get; set; }
        public virtual car_model car_model { get; set; }
    }
}
