//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car24project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_characteristic_value
    {
        public int id_car_characteristic_value { get; set; }
        public string value { get; set; }
        public string unit { get; set; }
        public Nullable<int> id_car_characteristic { get; set; }
        public Nullable<int> id_car_modification { get; set; }
    
        public virtual car_characteristic car_characteristic { get; set; }
        public virtual car_modification car_modification { get; set; }
    }
}
