//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car24project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_characteristic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public car_characteristic()
        {
            this.car_characteristic_value = new HashSet<car_characteristic_value>();
        }
    
        public int id_car_characteristic { get; set; }
        public string name { get; set; }
        public Nullable<int> id_parent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<car_characteristic_value> car_characteristic_value { get; set; }
    }
}
