//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car24project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reklam
    {
        public int id { get; set; }
        public byte[] photo { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string text { get; set; }
    }
}
