//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car24project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string login { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int countryID { get; set; }
        public int sityID { get; set; }
        public int genderID { get; set; }
        public byte[] photo { get; set; }
        public int usersTypeID { get; set; }
    
        public virtual countries countries { get; set; }
        public virtual gender gender { get; set; }
        public virtual sities sities { get; set; }
        public virtual usersType usersType { get; set; }
    }
}
